# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement

  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":lh"
    replace: "http://localhost"

  - trigger: ":email"
    replace: "gauthierkk@gmail.com"

  - trigger: ":github"
    replace: "https://github.com/Gauthierkk"

  - trigger: ":linkedin"
    replace: "https://www.linkedin.com/in/gauthier-kelly-700872170/"

  # Raycast

  - trigger: ":raycastdownload"
    replace: "bash ~/.config/raycast/download.sh"

  # Claude
  - trigger: ":claudesync"
    replace: "bash ~/.config/espanso/scripts/claudesync.sh"

  # Homebrew

  - trigger: ":brewup"
    replace: "brew update && brew upgrade"


  - trigger: ":brewdump"
    replace: "brew bundle dump --file=~/Documents/code/configs/homebrew/Brewfile --force --no-vscode"

  #Code

  - trigger: ":venv"
    replace: "source .venv/bin/activate"

  - trigger: ":makevenv"
    replace: "python3 -m venv .venv"

  #Git 

  - trigger: ":gch"
    replace: "git checkout"

  - trigger: ":gs"
    replace: "git status"

  - trigger: ":ga"
    replace: "git add *"

  - trigger: ":gcm"
    replace: "git commit -m \"$|$\""

  - trigger: ":gps"
    replace: "git push"

  - trigger: ":gpl"
    replace: "git pull"

  - trigger: ":gb"
    replace: "git branch"

  - trigger: ":gco"
    replace: "git checkout "

  - trigger: ":gnb"
    replace: "git checkout -b "

  - trigger: ":gfo"
    replace: "git fetch origin "

  - trigger: ":gdb"
    replace: 'git branch --merged | grep -v \"\*\|main\|dev\" | xargs -n 1 git branch -D'


  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"

  - trigger: ":today"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%x"
          locale: "en-US"

  # And much more! For more information, visit the docs: https://espanso.org/docs/